<?php

namespace App\DataFixtures;

class Data 
{
    public $brands = [
        0 => [
            "name" => "acebos",
            "logo" => "acebos.jpg",
        ],
        1 => [
            "name" => "babybotte",
            "logo" => "babybotte.jpg",
        ],
        2 => [
            "name" => "bellamy",
            "logo" => "bellamy.jpg",
        ],
        3 => [
            "name" => "bopy",
            "logo" => "bopy.jpg",
        ],
        4 => [
            "name" => "collonil",
            "logo" => "collonil.jpg",
        ],
        5 => [
            "name" => "Columbia",
            "logo" => "Columbia.jpg",
        ],
        6 => [
            "name" => "Colmar",
            "logo" => "Colmar.jpg",
        ],
        7 => [
            "name" => "Converse",
            "logo" => "Converse.jpg",
        ],
        8 => [
            "name" => "Creator",
            "logo" => "Creator.jpg",
        ],
        9 => [
            "name" => "delahaye",
            "logo" => "delahaye.jpg",
        ],
        10 => [
            "name" => "Dorking",
            "logo" => "Dorking.jpg",
        ],
        11 => [
            "name" => "DR MARTENS",
            "logo" => "DR MARTENS.jpg",
        ],
        12 => [
            "name" => "heydude",
            "logo" => "heydude.jpg",
        ],
        13 => [
            "name" => "eastpak",
            "logo" => "eastpak.jpg",
        ],
        14 => [
            "name" => "fargeot",
            "logo" => "fargeot.jpg",
        ],
        15 => [
            "name" => "fluchos",
            "logo" => "fluchos.jpg",
        ],
        16 => [
            "name" => "geox",
            "logo" => "geox.jpg",
        ],
        17 => [
            "name" => "graceandmila",
            "logo" => "graceandmila.jpg",
        ],
        18 => [
            "name" => "grisport",
            "logo" => "grisport.jpg",
        ],
        19 => [
            "name" => "JACK AND JONES",
            "logo" => "JACK AND JONES.jpg",
        ],
        20 => [
            "name" => "levis",
            "logo" => "levis.jpg",
        ],
        21 => [
            "name" => "kaporal",
            "logo" => "kaporal.jpg",
        ],
        22 => [
            "name" => "lacoste",
            "logo" => "lacoste.jpg",
        ],
        23 => [
            "name" => "timberland",
            "logo" => "timberland.jpg",
        ],
        24 => [
            "name" => "K DAQUES",
            "logo" => "K DAQUES.jpg",
        ]
    ];
    public $categories = [
        0 => [
            "name" => "Vêtements",
        ],
        1 => [
            "name" => "Maroquinerie",
        ],
        2 => [
            "name" => "Accessoires",
        ],
        3 => [
            "name" => "Chaussures",
        ]
    ];
    public $subCategories = [
        0 => [
            "name" => "Mid & Boots",
            "categorie_id" => "3",
        ],
        1 => [
            "name" => "Cirages",
            "categorie_id" => "1",
        ],
        2 => [
            "name" => "Sport",
            "categorie_id" => "3",
        ],
        3 => [
            "name" => "Sport Lifestyle",
            "categorie_id" => "3",
        ],
        4 => [
            "name" => "T. Shirts",
            "categorie_id" => "0",
        ],
        5 => [
            "name" => "Gilet sans manche",
            "categorie_id" => "0",
        ],
        6 => [
            "name" => "Ville Habillé",
            "categorie_id" => "3",
        ],
        7 => [
            "name" => "Sac Voyage",
            "categorie_id" => "1",
        ],
        8 => [
            "name" => "Sacs cartables",
            "categorie_id" => "1",
        ],
        9 => [
            "name" => "Pantoufle",
            "categorie_id" => "3",
        ],
        10 => [
            "name" => "Casual Chic",
            "categorie_id" => "3",
        ],
        11 => [
            "name" => "Outdoor Bas",
            "categorie_id" => "3",
        ],
    ];
    public $stores = [
        0 => [
            "name" => "Carré de la mode à La Primaube",
            "address" => "11 Avenue de Rodez",
            "zip_code" => "12450",
            "city" => "La Primaube",
            "country" => "FR",
            "phone" => "05 65 69 54 16",
        ],
        1 => [
            "name" => "Carré de la mode - Chaussures et maroquinerie à St-Affrique",
            "address" => "16 Boulevard Charles de Gaulle",
            "zip_code" => "12400",
            "city" => "Saint-Affrique",
            "country" => "FR",
            "phone" => "05 65 99 03 26",
        ],
        2 => [
            "name" => "Carré de la mode - Prêt-à-porter et maroquinerie à St-Affrique",
            "address" => "6 Boulevard de la République",
            "zip_code" => "12400",
            "city" => "Saint-Affrique",
            "country" => "FR",
            "phone" => "05 65 49 50 68",
        ],
        3 => [
            "name" => "Carré de la mode - Chaussures et maroquinerie à Réquista",
            "address" => "6 Boulevard de la République",
            "zip_code" => "12400",
            "city" => "Saint-Affrique",
            "country" => "FR",
            "phone" => "05 65 49 50 68",
        ],
    ];
    public $products = [
        0 => [
            "ref" => "6745801",
            "model" => "Acebos famille 1165 rouge multi cuir",
            "tag" => "",
            "ray" => "Garçon",
            "description" => "",
            "mark_id" => "0",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        1 => [
            "ref" => "6746401",
            "model" => "Acebos famille 3207 marine multi cuir",
            "tag" => "",
            "ray" => "Garçon",
            "description" => "",
            "mark_id" => "0",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        2 => [
            "ref" => "6153001",
            "model" => "Babybotte famille floel noir multi buck",
            "tag" => "",
            "ray" => "Fille",
            "description" => "",
            "mark_id" => "1",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        3 => [
            "ref" => "6153901",
            "model" => "Babybotte famille b2 marine multi buck",
            "tag" => "",
            "ray" => "Garçon",
            "description" => "",
            "mark_id" => "1",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        4 => [
            "ref" => "6142001",
            "model" => "Bellamy famille abbie blanc or cuir",
            "tag" => "Nouveau",
            "ray" => "Fille",
            "description" => "",
            "mark_id" => "2",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        5 => [
            "ref" => "6733601",
            "model" => "Bellamy famille lessy noir vernis",
            "tag" => "",
            "ray" => "Fille",
            "description" => "",
            "mark_id" => "2",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        6 => [
            "ref" => "6478402",
            "model" => "Bopy famille remigio marine multi vx",
            "tag" => "",
            "ray" => "Garçon",
            "description" => "",
            "mark_id" => "3",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        7 => [
            "ref" => "6742901",
            "model" => "Bopy famille jejou taupe buck",
            "tag" => "Nouveau",
            "ray" => "Garçon",
            "description" => "",
            "mark_id" => "3",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        8 => [
            "ref" => "7762101",
            "model" => "Collonil famille graisse collonil incolore",
            "tag" => "",
            "ray" => "ENTRETIEN",
            "description" => "La graisse COLLONIL est une graisse pour le cuir adaptée pour vos chaussures, sacs à main ou encore vos vêtements en cuir. En utilisant cette graisse, vos cuirs garderont leur flexibilité et leur résistance. Vos chaussures garderont leur souplesse et seront dotées d'une couche de protection déperlante.",
            "mark_id" => "4",
            "sub_categorie_id" => "1",
            "categorie_id" => "1",
        ],
        9 => [
            "ref" => "3985101",
            "model" => "Collonil famille eponge magic incolore",
            "tag" => "",
            "ray" => "ENTRETIEN",
            "description" => "Brosse magique pour cuir et synthétique. A la cire de Carmauba.",
            "mark_id" => "4",
            "sub_categorie_id" => "1",
            "categorie_id" => "1",
        ],
        10 => [
            "ref" => "6703001",
            "model" => "Columbia famille trailstorm mid waterproof noir multi goretex",
            "tag" => "",
            "ray" => "Femme",
            "description" => "",
            "mark_id" => "5",
            "sub_categorie_id" => "2",
            "categorie_id" => "3",
        ],
        11 => [
            "ref" => "6701801",
            "model" => "Columbia famille facet 30 outdry noir multi goretex",
            "tag" => "",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "5",
            "sub_categorie_id" => "2",
            "categorie_id" => "3",
        ],
        12 => [
            "ref" => "6774401",
            "model" => "Colmar famille travis drill noir",
            "tag" => "",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "6",
            "sub_categorie_id" => "3",
            "categorie_id" => "3",
        ],
        13 => [
            "ref" => "6774601",
            "model" => "Colmar famille travis sport bold rouge multi",
            "tag" => "",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "6",
            "sub_categorie_id" => "3",
            "categorie_id" => "3",
        ],
        14 => [
            "ref" => "6793601",
            "model" => "Creator famille b 2366 brun fonce cuir",
            "tag" => "Nouveau",
            "ray" => "Femme",
            "description" => "",
            "mark_id" => "8",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        15 => [
            "ref" => "6793901",
            "model" => "Creator famille ib 17576 cognac cuir",
            "tag" => "",
            "ray" => "Femme",
            "description" => "",
            "mark_id" => "8",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        16 => [
            "ref" => "7600702",
            "model" => "Delahaye famille 400 412 marine image ecriture",
            "tag" => "",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "9",
            "sub_categorie_id" => "4",
            "categorie_id" => "0",
        ],
        17 => [
            "ref" => "7600102",
            "model" => "Delahaye famille 400 250 marine",
            "tag" => "",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "9",
            "sub_categorie_id" => "5",
            "categorie_id" => "0",
        ],
        18 => [
            "ref" => "6487201",
            "model" => "Dorking famille d5794.su noir cuir",
            "tag" => "",
            "ray" => "Femme",
            "description" => "",
            "mark_id" => "10",
            "sub_categorie_id" => "6",
            "categorie_id" => "3",
        ],
        19 => [
            "ref" => "6666601",
            "model" => "Dr martens famille 1460 noir cuir",
            "tag" => "Nouveau",
            "ray" => "Femme",
            "description" => "",
            "mark_id" => "11",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        20 => [
            "ref" => "6666602",
            "model" => "Dr martens famille 1460 marron gras",
            "tag" => "Nouveau",
            "ray" => "Femme",
            "description" => "",
            "mark_id" => "11",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        21 => [
            "ref" => "6705101",
            "model" => "Eastpak famille reader m noir uni",
            "tag" => "",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "13",
            "sub_categorie_id" => "7",
            "categorie_id" => "1",
        ],
        22 => [
            "ref" => "6704021",
            "model" => "Eastpak famille padded pakér noir marron imprime",
            "tag" => "Nouveau",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "13",
            "sub_categorie_id" => "8",
            "categorie_id" => "1",
        ],
        23 => [
            "ref" => "6465501",
            "model" => "Fargeot famille bourdon marine",
            "tag" => "",
            "ray" => "Femme",
            "description" => "",
            "mark_id" => "14",
            "sub_categorie_id" => "9",
            "categorie_id" => "3",
        ],
        24 => [
            "ref" => "4429601",
            "model" => "Fargeot famille balabor marine",
            "tag" => "",
            "ray" => "Femme",
            "description" => "",
            "mark_id" => "14",
            "sub_categorie_id" => "9",
            "categorie_id" => "3",
        ],
        25 => [
            "ref" => "6050601",
            "model" => "Fluchos famille enlever noir cuir",
            "tag" => "",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "15",
            "sub_categorie_id" => "6",
            "categorie_id" => "3",
        ],
        26 => [
            "ref" => "4327301",
            "model" => "Fluchos famille laceflu noir cuir",
            "tag" => "",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "15",
            "sub_categorie_id" => "10",
            "categorie_id" => "3",
        ],
        27 => [
            "ref" => "6676603",
            "model" => "Geox famille j kalispera fille marine",
            "tag" => "",
            "ray" => "Femme",
            "description" => "",
            "mark_id" => "16",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        28 => [
            "ref" => "6675901",
            "model" => "Geox famille j kalispera fille marine",
            "tag" => "",
            "ray" => "Garçon",
            "description" => "",
            "mark_id" => "16",
            "sub_categorie_id" => "0",
            "categorie_id" => "3",
        ],
        29 => [
            "ref" => "4892301",
            "model" => "Grisport famille cameleon navy buck",
            "tag" => "Nouveau",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "18",
            "sub_categorie_id" => "11",
            "categorie_id" => "3",
        ],
        30 => [
            "ref" => "2980201",
            "model" => "Grisport famille tarbes marron goretex",
            "tag" => "Nouveau",
            "ray" => "Homme",
            "description" => "",
            "mark_id" => "18",
            "sub_categorie_id" => "11",
            "categorie_id" => "3",
        ],
    ];
    public $stocks = [
        0 => [
            "amount" => "15",
            "size" => "19",
            "color" => "Rouge",
            "matter" => "Cuir",
            "price" => "75.00",
            "product_id" => "0",
            "store_id" => "3",
        ],
        1 => [
            "amount" => "15",
            "size" => "20",
            "color" => "Rouge",
            "matter" => "Cuir",
            "price" => "75.00",
            "product_id" => "0",
            "store_id" => "3",
        ],
        2 => [
            "amount" => "15",
            "size" => "21",
            "color" => "Rouge",
            "matter" => "Cuir",
            "price" => "75.00",
            "product_id" => "0",
            "store_id" => "3",
        ],
        3 => [
            "amount" => "15",
            "size" => "24",
            "color" => "Marine",
            "matter" => "Cuir",
            "price" => "85.00",
            "product_id" => "1",
            "store_id" => "3",
        ],
        4 => [
            "amount" => "15",
            "size" => "25",
            "color" => "Marine",
            "matter" => "Cuir",
            "price" => "85.00",
            "product_id" => "1",
            "store_id" => "3",
        ],
        5 => [
            "amount" => "15",
            "size" => "26",
            "color" => "Marine",
            "matter" => "Cuir",
            "price" => "85.00",
            "product_id" => "1",
            "store_id" => "3",
        ],
        6 => [
            "amount" => "15",
            "size" => "27",
            "color" => "Marine",
            "matter" => "Cuir",
            "price" => "85.00",
            "product_id" => "1",
            "store_id" => "3",
        ],
        7 => [
            "amount" => "15",
            "size" => "28",
            "color" => "Marine",
            "matter" => "Cuir",
            "price" => "85.00",
            "product_id" => "1",
            "store_id" => "3",
        ],
        8 => [
            "amount" => "15",
            "size" => "29",
            "color" => "Marine",
            "matter" => "Cuir",
            "price" => "75.00",
            "product_id" => "1",
            "store_id" => "3",
        ],
        9 => [
            "amount" => "15",
            "size" => "21",
            "color" => "Noir",
            "matter" => "Buck",
            "price" => "85.00",
            "product_id" => "2",
            "store_id" => "3",
        ],
        10 => [
            "amount" => "15",
            "size" => "19",
            "color" => "Marine",
            "matter" => "Buck",
            "price" => "69.95",
            "product_id" => "3",
            "store_id" => "3",
        ],
        11 => [
            "amount" => "15",
            "size" => "24",
            "color" => "Blanc",
            "matter" => "Cuir",
            "price" => "79.95",
            "product_id" => "4",
            "store_id" => "3",
        ],
        12 => [
            "amount" => "15",
            "size" => "26",
            "color" => "Blanc",
            "matter" => "Cuir",
            "price" => "79.95",
            "product_id" => "4",
            "store_id" => "3",
        ],
        13 => [
            "amount" => "15",
            "size" => "24",
            "color" => "Noir",
            "matter" => "Vernis",
            "price" => "89.95",
            "product_id" => "5",
            "store_id" => "3",
        ],
        14 => [
            "amount" => "15",
            "size" => "25",
            "color" => "Noir",
            "matter" => "Vernis",
            "price" => "89.95",
            "product_id" => "5",
            "store_id" => "3",
        ],
        15 => [
            "amount" => "15",
            "size" => "22",
            "color" => "Marine",
            "matter" => "VX",
            "price" => "59.95",
            "product_id" => "6",
            "store_id" => "3",
        ],
        16 => [
            "amount" => "15",
            "size" => "19",
            "color" => "Marron",
            "matter" => "Buck",
            "price" => "59.95",
            "product_id" => "7",
            "store_id" => "3",
        ],
        17 => [
            "amount" => "15",
            "size" => "21",
            "color" => "Marron",
            "matter" => "Buck",
            "price" => "59.95",
            "product_id" => "7",
            "store_id" => "3",
        ],
        18 => [
            "amount" => "15",
            "size" => "23",
            "color" => "Marron",
            "matter" => "Buck",
            "price" => "59.95",
            "product_id" => "7",
            "store_id" => "3",
        ],
        19 => [
            "amount" => "20",
            "size" => "TU",
            "color" => "",
            "matter" => "",
            "price" => "7.00",
            "product_id" => "8",
            "store_id" => "1",
        ],
        20 => [
            "amount" => "20",
            "size" => "TU",
            "color" => "",
            "matter" => "",
            "price" => "7.00",
            "product_id" => "8",
            "store_id" => "2",
        ],
        21 => [
            "amount" => "20",
            "size" => "TU",
            "color" => "",
            "matter" => "",
            "price" => "5.00",
            "product_id" => "9",
            "store_id" => "1",
        ],
        22 => [
            "amount" => "20",
            "size" => "TU",
            "color" => "",
            "matter" => "",
            "price" => "5.00",
            "product_id" => "9",
            "store_id" => "2",
        ],
        23 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "10",
            "store_id" => "0",
        ],
        24 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "10",
            "store_id" => "1",
        ],
        25 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "10",
            "store_id" => "2",
        ],
        26 => [
            "amount" => "15",
            "size" => "38",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "10",
            "store_id" => "0",
        ],
        27 => [
            "amount" => "15",
            "size" => "38",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "10",
            "store_id" => "2",
        ],
        28 => [
            "amount" => "15",
            "size" => "39",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "10",
            "store_id" => "0",
        ],
        29 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "10",
            "store_id" => "0",
        ],
        30 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "10",
            "store_id" => "0",
        ],
        31 => [
            "amount" => "15",
            "size" => "42",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "10",
            "store_id" => "0",
        ],
        32 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "129.95",
            "product_id" => "11",
            "store_id" => "1",
        ],
        33 => [
            "amount" => "15",
            "size" => "42",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "129.95",
            "product_id" => "11",
            "store_id" => "1",
        ],
        34 => [
            "amount" => "15",
            "size" => "43",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "129.95",
            "product_id" => "11",
            "store_id" => "1",
        ],
        35 => [
            "amount" => "15",
            "size" => "44",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "129.95",
            "product_id" => "11",
            "store_id" => "1",
        ],
        36 => [
            "amount" => "15",
            "size" => "45",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "129.95",
            "product_id" => "11",
            "store_id" => "1",
        ],
        37 => [
            "amount" => "15",
            "size" => "46",
            "color" => "Noir",
            "matter" => "Goretex",
            "price" => "129.95",
            "product_id" => "11",
            "store_id" => "1",
        ],
        38 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Noir",
            "matter" => "",
            "price" => "125.00",
            "product_id" => "12",
            "store_id" => "1",
        ],
        39 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Noir",
            "matter" => "",
            "price" => "125.00",
            "product_id" => "12",
            "store_id" => "1",
        ],
        40 => [
            "amount" => "15",
            "size" => "42",
            "color" => "Noir",
            "matter" => "",
            "price" => "125.00",
            "product_id" => "12",
            "store_id" => "1",
        ],
        41 => [
            "amount" => "15",
            "size" => "43",
            "color" => "Noir",
            "matter" => "",
            "price" => "125.00",
            "product_id" => "12",
            "store_id" => "1",
        ],
        42 => [
            "amount" => "15",
            "size" => "44",
            "color" => "Noir",
            "matter" => "",
            "price" => "125.00",
            "product_id" => "12",
            "store_id" => "1",
        ],
        43 => [
            "amount" => "15",
            "size" => "45",
            "color" => "Noir",
            "matter" => "",
            "price" => "125.00",
            "product_id" => "12",
            "store_id" => "1",
        ],
        44 => [
            "amount" => "15",
            "size" => "46",
            "color" => "Noir",
            "matter" => "",
            "price" => "125.00",
            "product_id" => "12",
            "store_id" => "1",
        ],
        45 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Rouge",
            "matter" => "",
            "price" => "119.95",
            "product_id" => "13",
            "store_id" => "1",
        ],
        46 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Rouge",
            "matter" => "",
            "price" => "119.95",
            "product_id" => "13",
            "store_id" => "1",
        ],
        47 => [
            "amount" => "15",
            "size" => "42",
            "color" => "Rouge",
            "matter" => "",
            "price" => "119.95",
            "product_id" => "13",
            "store_id" => "1",
        ],
        48 => [
            "amount" => "15",
            "size" => "43",
            "color" => "Rouge",
            "matter" => "",
            "price" => "119.95",
            "product_id" => "13",
            "store_id" => "1",
        ],
        49 => [
            "amount" => "15",
            "size" => "44",
            "color" => "Rouge",
            "matter" => "",
            "price" => "119.95",
            "product_id" => "13",
            "store_id" => "1",
        ],
        50 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Marron",
            "matter" => "Cuir",
            "price" => "115.00",
            "product_id" => "14",
            "store_id" => "2",
        ],
        51 => [
            "amount" => "15",
            "size" => "38",
            "color" => "Marron",
            "matter" => "Cuir",
            "price" => "115.00",
            "product_id" => "14",
            "store_id" => "2",
        ],
        52 => [
            "amount" => "15",
            "size" => "39",
            "color" => "Marron",
            "matter" => "Cuir",
            "price" => "115.00",
            "product_id" => "14",
            "store_id" => "2",
        ],
        53 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Marron",
            "matter" => "Cuir",
            "price" => "115.00",
            "product_id" => "14",
            "store_id" => "2",
        ],
        54 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Marron",
            "matter" => "Cuir",
            "price" => "115.00",
            "product_id" => "14",
            "store_id" => "2",
        ],
        55 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Marron",
            "matter" => "Cuir",
            "price" => "99.95",
            "product_id" => "15",
            "store_id" => "2",
        ],
        56 => [
            "amount" => "15",
            "size" => "39",
            "color" => "Marron",
            "matter" => "Cuir",
            "price" => "99.95",
            "product_id" => "15",
            "store_id" => "2",
        ],
        57 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Marron",
            "matter" => "Cuir",
            "price" => "99.95",
            "product_id" => "15",
            "store_id" => "2",
        ],
        58 => [
            "amount" => "15",
            "size" => "M",
            "color" => "Marine",
            "matter" => "Image Ecriture",
            "price" => "69.95",
            "product_id" => "16",
            "store_id" => "0",
        ],
        59 => [
            "amount" => "15",
            "size" => "L",
            "color" => "Marine",
            "matter" => "",
            "price" => "119.00",
            "product_id" => "17",
            "store_id" => "0",
        ],
        60 => [
            "amount" => "15",
            "size" => "XL",
            "color" => "Marine",
            "matter" => "",
            "price" => "119.00",
            "product_id" => "17",
            "store_id" => "0",
        ],
        61 => [
            "amount" => "15",
            "size" => "2XL",
            "color" => "Marine",
            "matter" => "",
            "price" => "129.00",
            "product_id" => "17",
            "store_id" => "0",
        ],
        62 => [
            "amount" => "15",
            "size" => "36",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "79.95",
            "product_id" => "18",
            "store_id" => "1",
        ],
        63 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "79.95",
            "product_id" => "18",
            "store_id" => "1",
        ],
        64 => [
            "amount" => "15",
            "size" => "38",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "79.95",
            "product_id" => "18",
            "store_id" => "1",
        ],
        65 => [
            "amount" => "15",
            "size" => "39",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "79.95",
            "product_id" => "18",
            "store_id" => "1",
        ],
        66 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "79.95",
            "product_id" => "18",
            "store_id" => "1",
        ],
        67 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "79.95",
            "product_id" => "18",
            "store_id" => "1",
        ],
        68 => [
            "amount" => "15",
            "size" => "36",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "179.00",
            "product_id" => "19",
            "store_id" => "0",
        ],
        69 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "179.00",
            "product_id" => "19",
            "store_id" => "0",
        ],
        70 => [
            "amount" => "15",
            "size" => "39",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "179.00",
            "product_id" => "19",
            "store_id" => "0",
        ],
        71 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "179.00",
            "product_id" => "19",
            "store_id" => "0",
        ],
        72 => [
            "amount" => "15",
            "size" => "36",
            "color" => "Marron",
            "matter" => "Gras",
            "price" => "179.00",
            "product_id" => "20",
            "store_id" => "0",
        ],
        73 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Marron",
            "matter" => "Gras",
            "price" => "179.00",
            "product_id" => "20",
            "store_id" => "0",
        ],
        74 => [
            "amount" => "15",
            "size" => "38",
            "color" => "Marron",
            "matter" => "Gras",
            "price" => "179.00",
            "product_id" => "20",
            "store_id" => "0",
        ],
        75 => [
            "amount" => "15",
            "size" => "39",
            "color" => "Marron",
            "matter" => "Gras",
            "price" => "179.00",
            "product_id" => "20",
            "store_id" => "0",
        ],
        76 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Marron",
            "matter" => "Gras",
            "price" => "179.00",
            "product_id" => "20",
            "store_id" => "0",
        ],
        77 => [
            "amount" => "15",
            "size" => "TU",
            "color" => "Noir",
            "matter" => "Uni",
            "price" => "83.00",
            "product_id" => "21",
            "store_id" => "1",
        ],
        78 => [
            "amount" => "15",
            "size" => "TU",
            "color" => "Noir",
            "matter" => "Imprimé",
            "price" => "49.95",
            "product_id" => "22",
            "store_id" => "1",
        ],
        79 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Marine",
            "matter" => "",
            "price" => "39.95",
            "product_id" => "23",
            "store_id" => "3",
        ],
        80 => [
            "amount" => "15",
            "size" => "38",
            "color" => "Marine",
            "matter" => "",
            "price" => "39.95",
            "product_id" => "23",
            "store_id" => "3",
        ],
        81 => [
            "amount" => "15",
            "size" => "39",
            "color" => "Marine",
            "matter" => "",
            "price" => "39.95",
            "product_id" => "23",
            "store_id" => "3",
        ],
        82 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Marine",
            "matter" => "",
            "price" => "39.95",
            "product_id" => "23",
            "store_id" => "3",
        ],
        83 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Marine",
            "matter" => "",
            "price" => "39.95",
            "product_id" => "23",
            "store_id" => "3",
        ],
        84 => [
            "amount" => "15",
            "size" => "42",
            "color" => "Marine",
            "matter" => "",
            "price" => "39.95",
            "product_id" => "23",
            "store_id" => "3",
        ],
        85 => [
            "amount" => "15",
            "size" => "43",
            "color" => "Marine",
            "matter" => "",
            "price" => "39.95",
            "product_id" => "23",
            "store_id" => "3",
        ],
        86 => [
            "amount" => "15",
            "size" => "44",
            "color" => "Marine",
            "matter" => "",
            "price" => "39.95",
            "product_id" => "23",
            "store_id" => "3",
        ],
        87 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Marine",
            "matter" => "",
            "price" => "35.00",
            "product_id" => "24",
            "store_id" => "3",
        ],
        88 => [
            "amount" => "15",
            "size" => "38",
            "color" => "Marine",
            "matter" => "",
            "price" => "35.00",
            "product_id" => "24",
            "store_id" => "3",
        ],
        89 => [
            "amount" => "15",
            "size" => "39",
            "color" => "Marine",
            "matter" => "",
            "price" => "35.00",
            "product_id" => "24",
            "store_id" => "3",
        ],
        90 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Marine",
            "matter" => "",
            "price" => "35.00",
            "product_id" => "24",
            "store_id" => "3",
        ],
        91 => [
            "amount" => "15",
            "size" => "42",
            "color" => "Marine",
            "matter" => "",
            "price" => "35.00",
            "product_id" => "24",
            "store_id" => "3",
        ],
        92 => [
            "amount" => "15",
            "size" => "44",
            "color" => "Marine",
            "matter" => "",
            "price" => "35.00",
            "product_id" => "24",
            "store_id" => "3",
        ],
        93 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "125.00",
            "product_id" => "25",
            "store_id" => "0",
        ],
        94 => [
            "amount" => "15",
            "size" => "42",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "125.00",
            "product_id" => "25",
            "store_id" => "0",
        ],
        95 => [
            "amount" => "15",
            "size" => "43",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "125.00",
            "product_id" => "25",
            "store_id" => "0",
        ],
        96 => [
            "amount" => "15",
            "size" => "44",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "125.00",
            "product_id" => "25",
            "store_id" => "0",
        ],
        97 => [
            "amount" => "15",
            "size" => "45",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "125.00",
            "product_id" => "25",
            "store_id" => "0",
        ],
        98 => [
            "amount" => "15",
            "size" => "46",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "125.00",
            "product_id" => "25",
            "store_id" => "0",
        ],
        99 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "99.95",
            "product_id" => "26",
            "store_id" => "0",
        ],
        100 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "99.95",
            "product_id" => "26",
            "store_id" => "0",
        ],
        101 => [
            "amount" => "15",
            "size" => "42",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "99.95",
            "product_id" => "26",
            "store_id" => "0",
        ],
        102 => [
            "amount" => "15",
            "size" => "43",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "99.95",
            "product_id" => "26",
            "store_id" => "0",
        ],
        103 => [
            "amount" => "15",
            "size" => "44",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "99.95",
            "product_id" => "26",
            "store_id" => "0",
        ],
        104 => [
            "amount" => "15",
            "size" => "45",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "99.95",
            "product_id" => "26",
            "store_id" => "0",
        ],
        105 => [
            "amount" => "15",
            "size" => "46",
            "color" => "Noir",
            "matter" => "Cuir",
            "price" => "99.95",
            "product_id" => "26",
            "store_id" => "0",
        ],
        106 => [
            "amount" => "15",
            "size" => "36",
            "color" => "Marine",
            "matter" => "",
            "price" => "65.00",
            "product_id" => "27",
            "store_id" => "3",
        ],
        107 => [
            "amount" => "15",
            "size" => "37",
            "color" => "Marine",
            "matter" => "",
            "price" => "65.00",
            "product_id" => "27",
            "store_id" => "3",
        ],
        108 => [
            "amount" => "15",
            "size" => "24",
            "color" => "Marron",
            "matter" => "",
            "price" => "65.00",
            "product_id" => "28",
            "store_id" => "3",
        ],
        109 => [
            "amount" => "15",
            "size" => "25",
            "color" => "Marron",
            "matter" => "",
            "price" => "65.00",
            "product_id" => "28",
            "store_id" => "3",
        ],
        110 => [
            "amount" => "15",
            "size" => "26",
            "color" => "Marron",
            "matter" => "",
            "price" => "65.00",
            "product_id" => "28",
            "store_id" => "3",
        ],
        111 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Marine",
            "matter" => "Buck",
            "price" => "99.95",
            "product_id" => "29",
            "store_id" => "1",
        ],
        112 => [
            "amount" => "15",
            "size" => "42",
            "color" => "Marine",
            "matter" => "Buck",
            "price" => "99.95",
            "product_id" => "29",
            "store_id" => "1",
        ],
        113 => [
            "amount" => "15",
            "size" => "43",
            "color" => "Marine",
            "matter" => "Buck",
            "price" => "99.95",
            "product_id" => "29",
            "store_id" => "1",
        ],
        114 => [
            "amount" => "15",
            "size" => "44",
            "color" => "Marine",
            "matter" => "Buck",
            "price" => "99.95",
            "product_id" => "29",
            "store_id" => "1",
        ],
        115 => [
            "amount" => "15",
            "size" => "45",
            "color" => "Marine",
            "matter" => "Buck",
            "price" => "99.95",
            "product_id" => "29",
            "store_id" => "1",
        ],
        116 => [
            "amount" => "15",
            "size" => "46",
            "color" => "Marine",
            "matter" => "Buck",
            "price" => "99.95",
            "product_id" => "29",
            "store_id" => "1",
        ],
        117 => [
            "amount" => "15",
            "size" => "47",
            "color" => "Marine",
            "matter" => "Buck",
            "price" => "99.95",
            "product_id" => "29",
            "store_id" => "1",
        ],
        118 => [
            "amount" => "15",
            "size" => "40",
            "color" => "Marine",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "30",
            "store_id" => "1",
        ],
        119 => [
            "amount" => "15",
            "size" => "41",
            "color" => "Marine",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "30",
            "store_id" => "1",
        ],
        120 => [
            "amount" => "15",
            "size" => "42",
            "color" => "Marine",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "30",
            "store_id" => "1",
        ],
        121 => [
            "amount" => "15",
            "size" => "43",
            "color" => "Marine",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "30",
            "store_id" => "1",
        ],
        122 => [
            "amount" => "15",
            "size" => "44",
            "color" => "Marine",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "30",
            "store_id" => "1",
        ],
        123 => [
            "amount" => "15",
            "size" => "45",
            "color" => "Marine",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "30",
            "store_id" => "1",
        ],
        124 => [
            "amount" => "15",
            "size" => "46",
            "color" => "Marine",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "30",
            "store_id" => "1",
        ],
        125 => [
            "amount" => "15",
            "size" => "47",
            "color" => "Marine",
            "matter" => "Goretex",
            "price" => "99.95",
            "product_id" => "30",
            "store_id" => "1",
        ],
    ];
    public $deliveries = [
        0 => [
            "name" => "Mondial Relay",
            "threshold" => 50.00,
            "price_before" => 4.90,
            "price_after" => 0,
            "description" => "",
        ],
        1 => [
            "name" => "Colissimo à domicile",
            "threshold" => 60.00,
            "price_before" => 6.90,
            "price_after" => 0.00,
            "description" => "",
        ],
        2 => [
            "name" => "Retrait en magasin",
            "threshold" => 0,
            "price_before" => 0,
            "price_after" => 0,
            "description" => "",
        ],
    ];
}